spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: test
    password:

server:
  port: 8080

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: SpringBootRealm
  resource: springboot-client
  public-client: true
  principal-attribute: preferrd_username
  ssl-required: external
